### ISSUE TITLE
Race condition exception when accessing $Host.UI.psobject.Properties inside a runspace

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/ThreadJob#31]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Sporadic race condition exception when accessing `$Host.UI.psobject.Properties` inside a runspace started with `Start-ThreadJob`:

```powershell
1..500 | % {Start-ThreadJob {1 | Should -BeExactly 1; $supportsVT = $Host.UI.psobject.Properties['SupportsVirtualTerminal'].Value} -StreamingHost $Host} | Wait-Job | Receive-Job | Remove-Job -Force
```
[More details here.](https://github.com/pester/Pester/issues/2383)

### Expected behavior

```console
There should be no exception.
```

### Actual behavior

```console
InvalidOperation: Cannot index into a null array.
InvalidOperation: Cannot index into a null array.
InvalidOperation: Cannot index into a null array.
InvalidOperation: Cannot index into a null array.
```

### Error details

```console
PS C:\> Get-Error

Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot index into a null array.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : NullArray
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 26
            HistoryId        : -1
            Line             : 1 | Should -BeExactly 1; $supportsVT = $Host.UI.psobject.Properties['SupportsVirtualTerminal'].Value
            PositionMessage  : At line:1 char:26
                               + … eExactly 1; $supportsVT = $Host.UI.psobject.Properties['SupportsVirtu …
                               +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)
    Message     : Cannot index into a null array.
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure, CallSite, Object, String)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : NullArray
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 26
    HistoryId        : -1
    Line             : 1 | Should -BeExactly 1; $supportsVT = $Host.UI.psobject.Properties['SupportsVirtualTerminal'].Value
    PositionMessage  : At line:1 char:26
                       + … eExactly 1; $supportsVT = $Host.UI.psobject.Properties['SupportsVirtu …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

ThreadJob 2.0.3

### Visuals

![race](https://github.com/PowerShell/ThreadJob/assets/16168755/c5b17376-7bcc-44f9-a245-8dd1f310eb24)

**Comment by kilasuit** [comment]
I cannot repro this in 5.1 or 7.3.6 with the above command using Microsoft.PowerShell.ThreadJob v2.1.0 as per my comment in the pester thread outside of WT though just about to test this in WT to see if this does repro as above.

**Comment by kborowinski** [comment]
Where can I get the 2.1.0 version, so I could test it on Windows 10 and PowerShell 5.1 and 7.3.6? On PowerShell Gallery there is only 2.0.3. The same on GitHub repo.

**Comment by kilasuit** [comment]
`Install-Module Microsoft.PowerShell.ThreadJob` installs the renamed and updated ThreadJob module

**Comment by kborowinski** [comment]
Thanks, sorry, I've missed the info about the new module name. Will test it tomorrow. I've just finished a 9 hour car drive for the holidays so I wasn't thinking clearly.

**Comment by kilasuit** [comment]
Adding this snippet from the Discord discussion yesterday from @seeminglyscience as another way to repro this

```powershell
$event = [System.Threading.ManualResetEvent]::new($false)
$jobs = 1..500 | % {
    Start-ThreadJob {
        $event = $using:event
        $null = $event.WaitOne()
        $supportsVT = $Host.UI.psobject.Properties['SupportsVirtualTerminal'].Value
    } -StreamingHost $Host
}

Start-Sleep -Milliseconds 500
$null = $event.Set()

$jobs | Receive-Job -AutoRemoveJob -Wait
```

**Comment by SteveL-MSFT** [comment]
Based on the callstack, it appears that ListDictionary is being used somewhere which is not threadsafe.  In this case, this doesn't appear to be an issue with ThreadJob itself, but something the thread is accessing is not threadsafe and results in the race condition.

If the actual use case is to see within a thread if `SupportsVirtualTerminal` is true/false, then it would be best to capture that outside of the thread job and pass it in.

**Comment by SeeminglyScience** [comment]
I would agree that I don't think it's a ThreadJob problem. My guess is that it's a race condition in how PowerShell is creating the internal `PSMemberInfoCollection<>` and caching it in the member resurrection table.

At a glance it looks like there's a lock around the creation of the underlying collection, but the collection itself is populated lazily with no lock.
